#!/bin/bash
# Slurm stuff
mkdir -p /etc/slurm &>/dev/null
chmod 777 /etc/slurm

cat << EOF > /etc/slurm/slurm.conf
# slurm.conf file generated by configurator.html.
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ClusterName=localcluster
SlurmctldHost=localhost
#ControlMachine=localhost
MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/lib/slurm/slurmd
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm/slurmctld
SwitchType=switch/none
TaskPlugin=task/none
#
# TIMERS
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
#
#AccountingStoragePort=
AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log
#
# COMPUTE NODES
#NodeName=localhost CPUs=10 RealMemory=50000 State=IDLE Features=oversubscribe
PartitionName=LocalQ Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOF

ls /etc/slurm
ln -s /etc/slurm/slurm.conf /etc/slurm.conf
chmod 755 /etc/slurm/

slurmd -C | head -n 1
#slurmd -C | head -n 1 >> /etc/slurm/slurm.conf
sed -E 's/^(NodeName=)[^ ]+/\1localhost/' <<< "$(slurmd -C | head -n 1)" >> /etc/slurm/slurm.conf


## Servoce config
#service munge start
#service slurmd start
#service slurmctld start

# REset state and show info
#scontrol update nodename=localhost state=IDLE
#sinfo --all
